### ISSUE TITLE
Add Open / close menu

### ISSUE THREAD

**Issue by withrvr** [HarshKapadia2/git-graph#4]
something like menu

when we can see for selected commits only

- single
- multiple
- close all
- open all

like this

**Comment by HarshKapadia2** [comment]
Makes sense! Good idea, @withrvr! Thank you!

**Comment by HarshKapadia2** [comment]
Would you like to open a PR for this?

**Comment by HarshKapadia2** [comment]
I've built the feature as well as I can, but it probably can be optimized. I'll look into optimizations whenever I can think of a way to do something.
