### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by atrent** [HarshKapadia2/git-graph#56]
In the README you begin usage instructions with "Select..." but you do not explain how to run this thing.
I'm on debian, form the shell, I do not see any executable files.
Thank you

**Comment by HarshKapadia2** [comment]
Hi @atrent, this is a web app that can be accessed at [git-graph.harshkapadia.me](https://git-graph.harshkapadia.me). To use it locally, it will have to be built using instructions in https://github.com/HarshKapadia2/git-graph/blob/main/CONTRIBUTING.md.

Please let me know if you have any other questions. Thank you!
